services:
  - type: web
    name: streamflow-music
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ALLOWED_ORIGINS
        value: https://streamflow-music.onrender.com
    autoDeploy: true
    plan: free
